# Generated by Django 5.2.1 on 2025-07-02 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userscore_delete_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='quiz_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.types'),
        ),
    ]
